OLED_ENABLE = no
MOUSEKEY_ENABLE = yes

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c
# # POINTING_DEVICE_GESTURES_ENABLE = yes
# # POINTING_DEVICE_CURSOR_GLIDE_ENABLE = yes
# # CIRQUE_PINNACLE_POSITION_MODE = CIRQUE_PINNACLE_RELATIVE_MODE
# # CIRQUE_PINNACLE_POSITION_MODE = yes
# CIRQUE_PINNACLE_POSITION_MODE = CIRQUE_PINNACLE_ABSOLUTE_MODE
# CIRQUE_PINNACLE_TAP_ENABLE = yes
# CIRQUE_PINNACLE_SIDE_SCROLL_ENABLE = yes
# # CIRQUE_PINNACLE_CURVED_OVERLAY = yes
CIRQUE_PINNACLE_DIAMETER_MM = 35


SEND_STRING_ENABLE = yes
# OLED_DRIVER = SSD1306   # Enables the use of OLED displays
# ENCODER_ENABLE = yes       # Enables the use of one or more encoders
RGBLIGHT_ENABLE = no      # Enable keyboard RGB underglow
